version: "3.8"

services:
  web:
    image: nginx:alpine
    ports:
      - "80:80/tcp"
      - "443:443/tcp"

  dns:
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
