name: CI

on:
    push:
        branches: [main, feat/*, fix/*]
    pull_request:
        branches: [main]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    typecheck:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                  version: 8
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "pnpm"
            - run: pnpm install --frozen-lockfile
            - run: pnpm run typecheck

    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                  version: 8
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "pnpm"
            - run: pnpm install --frozen-lockfile
            - run: pnpm run lint

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                  version: 8
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "pnpm"
            - run: pnpm install --frozen-lockfile
            - run: pnpm run test

    e2e:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                  version: 8
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "pnpm"
            - run: pnpm install --frozen-lockfile
            - run: pnpm --filter web exec playwright install --with-deps
            - run: pnpm run build
            - run: pnpm --filter web run test:e2e
              if: hashFiles('apps/web/e2e') != ''

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                  version: 8
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "pnpm"
            - run: pnpm install --frozen-lockfile
            - run: pnpm run build
